name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v2
      with:
        name: tl
        path: /home/runner/work/tasklist-cli/tasklist-cli/target/debug/tasklist-cli.exe
