name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
    - run: rustup target add x86_64-pc-windows-gnu
    - run: rustup toolchain install stable-x86_64-pc-windows-gnu
    - run: sudo apt-get install gcc-mingw-w64
    - name: Build
      run: cargo build --target x86_64-pc-windows-gnu --release --verbose
    - name: Hash
      run: sha512sum tl.exe | cut -d " " -f 1 > checksum
      working-directory: /home/runner/work/tasklist/tasklist/target/x86_64-pc-windows-gnu/release/
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      id: semantic
      with:
        branch: main
      working-directory: /home/runner/work/tasklist/tasklist/target/x86_64-pc-windows-gnu/release/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}