name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Create Release
      run: gh release create ${GITHUB_SHA::6} /home/runner/work/tasklist-cli/tasklist-cli/target/release/tasklist-cli
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}