name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
    - name: GitHub CLI Auth
      run: gh auth login --with-token
    - name: Create Release
      run: gh release create v1.2.3 tl/tasklist-cli