name: Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
  steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build.yml
    - name: Create Release
      run: gh release create v1.2.3