name: Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup target add x86_64-pc-windows-gnu
    - run: rustup toolchain install stable-x86_64-pc-windows-gnu
    - run: rustup toolchain install x86_64-w64-mingw32-gcc
    - run: sudo apt-get install gcc-mingw-w64
    - name: Build
      run: cargo build --target x86_64-pc-windows-gnu --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Create Release
      run: gh release create ${GITHUB_SHA::6} /home/runner/work/tasklist-cli/tasklist-cli/target/release/tasklist-cli.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}